const MAIN_ROUTE = '/';
const REGISTRATION_ROUTE = '/registration';
const AUTH_ROUTE = '/login';
const NOTFOUND_ROUTE = '/404';
const DEFAULT_ROUTE = '*';

export { MAIN_ROUTE, DEFAULT_ROUTE, REGISTRATION_ROUTE, AUTH_ROUTE, NOTFOUND_ROUTE };
