const DEFAULT_ROUTE = '/';
const REGISTRATION_ROUTE = '/registration';
const AUTH_ROUTE = '/login';
const NOTFOUND_ROUTE = '*';

export { DEFAULT_ROUTE, REGISTRATION_ROUTE, AUTH_ROUTE, NOTFOUND_ROUTE };
